server:
  port: 9080

spring:
  profiles:
    include: @bootdemo.profile@
    application:
      name: bootapplication
      token-name: X-TOKEN
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl