spring:
  datasource:
    username: root
    password: 11111111
    url: jdbc:mysql://127.0.0.1:3306/testdb01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
